name: Continuous Deployment

on:
  # push: 
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install latest Docker compose
        run: |
          VERSION=$(curl --silent https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')
          INSTALLED_VERSION=v$(docker-compose --version 2>/dev/null | grep -Po '\d+\.\d+\.\d+')
          if [ "$INSTALLED_VERSION" != "$VERSION" ]; then
            echo "Installing/Updating docker-compose to version $VERSION from $INSTALLED_VERSION"
            DESTINATION=/usr/local/bin/docker-compose
            sudo curl -L https://github.com/docker/compose/releases/download/${VERSION}/docker-compose-$(uname -s)-$(uname -m) -o $DESTINATION
            sudo chmod +x $DESTINATION
          else
            echo "docker-compose is already up-to-date."
          fi

      - name: Deploy to VM
        run: |
          sudo docker-compose down -v && sudo docker-compose up -d --build
